//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMod.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharpModExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharpModExceptionResources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpMod.Exceptions.SharpModExceptionResources", typeof(SharpModExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error allocating structure.
        /// </summary>
        internal static string ERROR_ALLOC_STRUCT {
            get {
                return ResourceManager.GetString("ERROR_ALLOC_STRUCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device number out of range.
        /// </summary>
        internal static string ERROR_DEVICE_NUMBER_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ERROR_DEVICE_NUMBER_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver error.
        /// </summary>
        internal static string ERROR_DRIVER {
            get {
                return ResourceManager.GetString("ERROR_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading header.
        /// </summary>
        internal static string ERROR_LOADING_HEADER {
            get {
                return ResourceManager.GetString("ERROR_LOADING_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading pattern.
        /// </summary>
        internal static string ERROR_LOADING_PATTERN {
            get {
                return ResourceManager.GetString("ERROR_LOADING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading sampleinfo.
        /// </summary>
        internal static string ERROR_LOADING_SAMPLEINFO {
            get {
                return ResourceManager.GetString("ERROR_LOADING_SAMPLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading track.
        /// </summary>
        internal static string ERROR_LOADING_TRACK {
            get {
                return ResourceManager.GetString("ERROR_LOADING_TRACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown module format.
        /// </summary>
        internal static string ERROR_NOT_A_MODULE {
            get {
                return ResourceManager.GetString("ERROR_NOT_A_MODULE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening file.
        /// </summary>
        internal static string ERROR_OPENING_FILE {
            get {
                return ResourceManager.GetString("ERROR_OPENING_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of sample-handles.
        /// </summary>
        internal static string ERROR_OUT_OF_HANDLES {
            get {
                return ResourceManager.GetString("ERROR_OUT_OF_HANDLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t open output file.
        /// </summary>
        internal static string ERROR_OUTPUT_FILE {
            get {
                return ResourceManager.GetString("ERROR_OUTPUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample too big, out of memory.
        /// </summary>
        internal static string ERROR_SAMPLE_TOO_BIG {
            get {
                return ResourceManager.GetString("ERROR_SAMPLE_TOO_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any of the supported sound-devices.
        /// </summary>
        internal static string ERROR_UNSUPPORTED_SOUND_DEVICE {
            get {
                return ResourceManager.GetString("ERROR_UNSUPPORTED_SOUND_DEVICE", resourceCulture);
            }
        }
    }
}
