using System;
using System.Collections.Generic;
using System.Text;

namespace SharpMod.Player
{
	public enum ActionsEnum
	{       
		UI_NEXT_SONG = 10,
		UI_RESTART = 11,
		UI_PREVIOUS_SONG = 12,
		UI_LOAD_SONG = 13,
		UI_SET_BPM = 14,
		UI_JUMP_TO_NEXT_PATTERN = 15,
		UI_RESTART_PATTERN = 17,
		UI_JUMP_TO_PREV_PATTERN = 17,
		UI_QUIT = 16,
		UI_DISPLAY = 17,
		UI_PAUSE = 18,
		UI_SPEED_UP = 19,
		UI_SLOW_DOWN = 20,
		UI_NORMAL_SPEED = 21,
		UI_VOL_UP = 22,
		UI_VOL_DOWN = 23,
		UI_NORMAL_VOL = 24,
		UI_MARK_DELETED = 25,
		UI_DELETE_MARKED = 26,
		UI_SELECT_MONO = 27,
		UI_SELECT_STEREO = 28,
		UI_SELECT_INTERP = 29,
		UI_SELECT_NONINTERP = 30,
		UI_SELECT_8BIT = 31,
		UI_SELECT_16BIT = 32,
        DEFAULT = 9999
	}
}
